In [1]:
import tensorflow as tf
import numpy as np

tfs = tf.InteractiveSession()
hello = tf.constant('Hello Tensorflow!')
print(tfs.run(hello))

b'Hello Tensorflow!'


In [2]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')
print('c1 (x):', c1)
print('c2 (y):', c2)
print('c3 (z):', c3)

print('run([c1, c2, c3]):', tfs.run([c1, c2, c3]))

c1 (x): Tensor("x:0", shape=(), dtype=int32)
c2 (y): Tensor("y:0", shape=(), dtype=float32)
c3 (z): Tensor("z:0", shape=(), dtype=float32)
run([c1, c2, c3]): [5, 6.0, 7.0]


In [4]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)
print('op1:', op1)
print('op2:', op2)

print('run(op1):', tfs.run(op1))
print('run(op2):', tfs.run(op2))

op1: Tensor("Add_1:0", shape=(), dtype=float32)
op2: Tensor("Mul_1:0", shape=(), dtype=float32)
run(op1): 13.0
run(op2): 42.0


In [8]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1:', p1)
print('p2:', p2)

op4 = p1 * p2
print('run(op4, {p1:2.0, p2:3.0}) :', tfs.run(op4, {p1:2.0, p2:3.0}))

print('run(op4, feed_dict={p1:3.0, p2:4.0}) :', tfs.run(op4, feed_dict={p1:3.0, p2:4.0}))

print('run(op4, feed_dict={p1:[2.0, 3.0, 4.0], p2:[3.0, 4.0, 5.0]})', 
     tfs.run(op4, feed_dict={p1:[2.0, 3.0, 4.0], p2:[3.0, 4.0, 5.0]}))

p1: Tensor("Placeholder_6:0", dtype=float32)
p2: Tensor("Placeholder_7:0", dtype=float32)
run(op4, {p1:2.0, p2:3.0}) : 6.0
run(op4, feed_dict={p1:3.0, p2:4.0}) : 12.0
run(op4, feed_dict={p1:[2.0, 3.0, 4.0], p2:[3.0, 4.0, 5.0]}) [ 6. 12. 20.]


In [3]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)
print('tf_t:', tf_t)
print('run(tf_t):', tfs.run(tf_t))

a1dim = np.array([1, 2, 3, 4, 5.99])
print('a1dim shape:', a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)
print('tf_t:', tf_t)
print('tf_t[0]:', tf_t[0])
print('tf_t[2]:', tf_t[2])
print('run(tf_t):\n', tfs.run(tf_t))

tf_t: Tensor("Const_2:0", shape=(), dtype=float64)
run(tf_t): 5.0
a1dim shape: (5,)
tf_t: Tensor("Const_3:0", shape=(5,), dtype=float64)
tf_t[0]: Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[2]: Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_t):
 [1.   2.   3.   4.   5.99]


In [5]:
a2dim = np.array([(1,2,3,4,5.99),
                 (2,3,4,5,6.99),
                 (3,4,5,6,7.99)])
print('a2dim shape:', a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)
print('tf_t:', tf_t)
print('tf_t[0][0]:', tf_t[0][0])
print('tf_t[1][2]:', tf_t[1][2])
print('run(tf_t):\n', tfs.run(tf_t))

a2dim shape: (3, 5)
tf_t: Tensor("Const_4:0", shape=(3, 5), dtype=float64)
tf_t[0][0]: Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2]: Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t):
 [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


In [6]:
a3dim = np.array([[[1,2],[3,4]],
                 [[5,6], [7,8]]
                 ])
print('a3dim shape:', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)
print('tf_t:', tf_t)
print('tf_t[0][0][0]:', tf_t[0][0][0])
print('tf_t[1][1][1]:', tf_t[1][1][1])
print('run(tf_t):\n', tfs.run(tf_t))

a3dim shape: (2, 2, 2)
tf_t: Tensor("Const_5:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0]: Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1]: Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t):
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
